#%RAML 1.0 Library
usage: library for all resource types

resourceTypes:
  all:
    get?:
      responses:
        200:
          body:
            application/json:
              type: <<getResponseType>>
    post?:
      body:
        application/type:
          type: <<postRequestType>>
      responses:
        201:
          body:
            application/json:
              type: <<postResponseType>>
    put?:
      body:
        application/type:
          type: <<putRequestType>>
      responses:
        200:
          body:
            application/json:
              type: <<putResponseType>>              