#%RAML 1.0 Trait
usage: Apply this to enforce client id & secret
headers:
  client_id:
    description: Client Id for authenticaton
    type: string
    required: true
  client_secret:
    description: Client Secret for authentication
    type: string
    required: true